### PR TITLE
Add a screenshot

### PR DESCRIPTION
**Pull request by wezm**
This PR adds a screenshot to the README to help new users get a feel for the UI.

### CODE REVIEW

**Comment by raftario** [comment]
Don't mind the checks, my fault for not checking the Clippy warnings.

**Comment by raftario** [comment]
The links also seems to be broken on your repo, I'd stick to a relative one to be safe. It would also be cleaner to use Firefox's full page capture feature.

**Comment by wezm** [comment]
Eh sorry about those fairly obvious oversights. :man_facepalming: Updated addressing comments. [Rendered README](https://github.com/raftario/filite/blob/521c59e4aea6f2ade1bab54b7d3c311fb2226f3c/README.md).

**Comment by raftario** [comment]
No problem, I couldn't say much anyway seeing how the code doesn't even pass my own checks 😅. Thanks for the PR, didn't expect one that fast!

**Pull request merged**
